/// The English source text for every translatable label in the customer app.
///
/// This map is the fallback shown when a translation has not arrived yet, and
/// it is also what gets posted to `POST /translations/sync` so the server can
/// translate and store the strings. Keys are `group.name`; the group is what
/// the admin Website Translations screen filters on, so keep it meaningful.
const Map<String, String> kAppStringsEn = <String, String>{
  // --- account -----------------------------------------------------------------
  'account.email_optional': 'Email (optional)',
  'account.profile_details': 'Profile Details',
  'account.profile_photo': 'Profile Photo',

  // --- address -----------------------------------------------------------------
  'address.add': 'Add Address',
  'address.add_delivery': 'Add a delivery address',
  'address.add_new': 'Add new address',
  'address.add_short': 'Add',
  'address.choose': 'Choose delivery address',
  'address.deliver_to_label': 'Deliver to {address}',
  'address.delivery_address': 'Delivery Address',
  'address.full_name': 'Full Name',
  'address.mobile': 'Mobile Number',
  'address.name': 'Name',
  'address.not_available': 'Address not available',
  'address.pincode': 'Pincode',
  'address.required': 'Address Required',
  'address.required_message': 'Enter name, mobile, address, city, state and pincode.',
  'address.save': 'Save Address',
  'address.save_failed': 'Save Failed',
  'address.saved_message': 'Delivery address has been saved.',
  'address.saved_title': 'Address Saved',
  'address.state': 'State',

  // --- auth --------------------------------------------------------------------
  'auth.brand_tagline': 'Healthy farms, trusted products',
  'auth.checking': 'Checking...',
  'auth.confirm_new_password': 'Confirm New Password',
  'auth.create_account': 'Register',
  'auth.create_account_title': 'Create Account',
  'auth.create_verify': 'Create & Verify OTP',
  'auth.creating': 'Creating...',
  'auth.current_password': 'Current Password',
  'auth.customer_login_subtitle': 'Login to buy farm medicine, seeds and agriculture essentials.',
  'auth.customer_registration': 'Customer Registration',
  'auth.email_address': 'Email Address',
  'auth.email_address_optional': 'Email Address (optional)',
  'auth.email_login': 'Email Login',
  'auth.email_or_blank': 'Enter valid email address or leave it blank.',
  'auth.email_required': 'Email Required',
  'auth.enter_full_name': 'Enter customer full name.',
  'auth.enter_otp': 'Enter 6 digit OTP.',
  'auth.enter_valid_email': 'Enter a valid email address.',
  'auth.enter_valid_mobile': 'Enter valid mobile number.',
  'auth.hide_password': 'Hide password',
  'auth.invalid_email': 'Invalid Email',
  'auth.invalid_response': 'Invalid login response from server.',
  'auth.login_failed': 'Login Failed',
  'auth.mobile': 'Mobile',
  'auth.mobile_otp': 'Mobile OTP',
  'auth.mobile_required': 'Mobile Required',
  'auth.name_optional': 'Name (optional)',
  'auth.name_required': 'Name Required',
  'auth.new_customer': 'New customer? ',
  'auth.new_password': 'New Password',
  'auth.otp_failed': 'OTP Failed',
  'auth.otp_label': '6 Digit OTP',
  'auth.otp_primary_note': 'Mobile OTP is currently the primary backend login method.',
  'auth.otp_required': 'OTP Required',
  'auth.otp_sent_to': 'Enter OTP sent to {mobile}',
  'auth.otp_subtitle': 'We will send a 6 digit OTP to your mobile number.',
  'auth.otp_verification': 'OTP Verification',
  'auth.password': 'Password',
  'auth.password_min': 'Password must be at least 6 characters.',
  'auth.password_optional': 'Password (optional)',
  'auth.password_required': 'Password Required',
  'auth.register_free': 'Register free. Product purchase and order tracking will be available after login.',
  'auth.resend_otp': 'Resend OTP',
  'auth.send_otp': 'Send OTP',
  'auth.sending_otp': 'Sending OTP...',
  'auth.show_password': 'Show password',
  'auth.signup_failed': 'Signup Failed',
  'auth.token_missing': 'Login token missing from server response.',
  'auth.verify_continue': 'Verify & Continue',
  'auth.verify_otp': 'Verify OTP',
  'auth.verifying': 'Verifying...',
  'auth.welcome_back': 'Welcome Back',

  // --- cart --------------------------------------------------------------------
  'cart.change': 'Change',
  'cart.deliver_to': 'Deliver to',
  'cart.empty_checkout_message': 'Add products before checkout.',
  'cart.empty_checkout_title': 'Cart Empty',
  'cart.empty_hint': 'Add medicines, seeds or farm products to start your order.',
  'cart.empty_text': 'Your cart is empty.',
  'cart.empty_title': 'Your cart is empty',
  'cart.gst_note': 'GST and the final amount are confirmed on your invoice.',
  'cart.item_total': 'Item total',
  'cart.move_to_cart': 'Move to cart',
  'cart.only_left': 'Only {n} left',
  'cart.price_details': 'Price Details',
  'cart.price_items': 'Price ({n} items)',
  'cart.proceed_to_buy': 'Proceed to Buy',
  'cart.remove_title': 'Remove from cart?',
  'cart.saved_for_later_n': 'Saved for later ({n})',
  'cart.subtotal_items': 'Subtotal ({count}): ',
  'cart.title': 'Cart',
  'cart.total': 'Total',
  'cart.total_amount': 'Total Amount',
  'cart.total_count': 'Total · {count}',
  'cart.will_save': 'You will save {amount} on this order',
  'cart.you_save': 'You save {amount}',

  // --- catalog -----------------------------------------------------------------
  'catalog.add_to_cart': 'Add to Cart',
  'catalog.animal_medicine': 'Animal Medicine',
  'catalog.bank_offers': 'Bank & Wallet Offers',
  'catalog.buy_now': 'Buy Now',
  'catalog.coupon_copied': 'Coupon code {code} copied',
  'catalog.default_description': 'Use this product as per label instructions and professional guidance. Keep it stored safely and away from children.',
  'catalog.default_short_description': 'Premium quality product for farm and livestock care.',
  'catalog.hero_subtitle': 'Medicines, Seeds & Supplements',
  'catalog.hero_title': 'Farm Health Essentials',
  'catalog.new_arrivals': 'New Arrivals',
  'catalog.no_products_customer': 'No product found in selected category.',
  'catalog.no_products_title': 'No Products',
  'catalog.preparing_store': 'Preparing storefront...',
  'catalog.product_details': 'Product Details',
  'catalog.search_home_hint': 'Search medicines, seeds, fertilizers...',
  'catalog.search_product': 'Search product',
  'catalog.shop_by_category': 'Shop By Category',
  'catalog.shop_now': 'Shop Now',
  'catalog.store_services': 'Store Services',
  'catalog.top_selling': 'Top Selling Items',

  // --- checkout ----------------------------------------------------------------
  'checkout.address_required_message': 'Enter delivery name, mobile, address, city, state and pincode.',
  'checkout.cod_long': 'Cash on Delivery / Pay on Delivery',
  'checkout.delivery_details': 'Delivery Details',
  'checkout.no_address': 'No saved address',
  'checkout.no_address_fill': 'Add one, or fill the delivery details below.',
  'checkout.notes': 'Order Notes',
  'checkout.online_soon': 'Online Payment (Coming Soon)',
  'checkout.order_failed': 'Order Failed',
  'checkout.order_placed': 'Order Placed',
  'checkout.order_placed_message': 'Your order has been sent to admin for processing.',
  'checkout.payment_method': 'Payment Method',
  'checkout.place_order': 'Place Order {amount}',
  'checkout.placing': 'Placing Order...',
  'checkout.title': 'Checkout',

  // --- common ------------------------------------------------------------------
  'common.added': 'Added',
  'common.added_to_cart': '{name} added to cart',
  'common.address': 'Address',
  'common.bank_transfer': 'Bank Transfer',
  'common.buy_again': 'Buy again',
  'common.cancel': 'Cancel',
  'common.case_many': '{n} cases',
  'common.case_one': '{n} case',
  'common.cases_units': '{qty} · {units} units/case',
  'common.cash_on_delivery': 'Cash on Delivery',
  'common.city': 'City',
  'common.copied': 'Copied',
  'common.customer': 'Customer',
  'common.default': 'Default',
  'common.delete': 'Delete',
  'common.description': 'Description',
  'common.email': 'Email',
  'common.in_stock': 'In stock',
  'common.item_count_many': '{n} items',
  'common.item_count_one': '{n} item',
  'common.loading': 'Loading...',
  'common.login': 'Login',
  'common.logout_message': 'You will need to log in again to place orders.',
  'common.logout_title': 'Logout?',
  'common.message': 'Message',
  'common.network_failed': 'Network request failed',
  'common.no_internet': 'No internet connection.',
  'common.no_items': 'No items found for this order.',
  'common.not_added': 'Not added',
  'common.notes': 'Notes',
  'common.out_of_stock': 'Out of stock',
  'common.payment': 'Payment',
  'common.pending': 'Pending',
  'common.preparing': 'Preparing...',
  'common.products': 'Products',
  'common.qty': 'Qty {n}',
  'common.remove': 'Remove',
  'common.remove_from_wishlist': 'Remove from wishlist',
  'common.request_failed': 'Request failed',
  'common.required': 'Required',
  'common.save_for_later': 'Save for later',
  'common.saving': 'Saving...',
  'common.see_all': 'See All',
  'common.sending': 'Sending...',
  'common.submitting': 'Submitting...',
  'common.use': 'Use',
  'common.view_all': 'View All',

  // --- home --------------------------------------------------------------------
  'home.copy': 'Copy',

  // --- invoice -----------------------------------------------------------------
  'invoice.amount_details': 'Amount details',
  'invoice.could_not_download': 'Could not download the invoice.',
  'invoice.could_not_load': 'This invoice could not be loaded.',
  'invoice.discount': 'Discount',
  'invoice.download': 'Download PDF',
  'invoice.download_failed': 'Download failed',
  'invoice.empty_message': 'An invoice appears here once your order is billed.',
  'invoice.empty_title': 'No invoices yet',
  'invoice.grand_total': 'Grand total',
  'invoice.gst': 'GST',
  'invoice.invoice_date': 'Invoice date',
  'invoice.items': 'Items',
  'invoice.loading': 'Loading invoice...',
  'invoice.loading_list': 'Loading invoices...',
  'invoice.no_match_message': 'Try a different invoice or order number.',
  'invoice.no_match_title': 'No matching invoice',
  'invoice.no_viewer': 'Saved to your device, but no PDF viewer is installed to open it.',
  'invoice.not_found': 'Invoice not found.',
  'invoice.preparing': 'Preparing PDF...',
  'invoice.saved': 'Invoice saved',
  'invoice.saved_as_file': 'Saved as {file}',
  'invoice.search_hint': 'Search invoice or order number',
  'invoice.subtotal': 'Subtotal',
  'invoice.title': 'Invoice',
  'invoice.total_amount': 'Total amount',
  'invoice.unavailable': 'Invoice unavailable',
  'invoice.view': 'View Invoice',
  'invoice.view_short': 'View',

  // --- language ----------------------------------------------------------------
  'language.subtitle': 'Product names and app text will be shown in this language.',
  'language.title': 'Choose your language',
  'language.updating': 'Applying language...',

  // --- login -------------------------------------------------------------------
  'login.before_address': 'Please login or sign up to add a delivery address.',
  'login.before_buy': 'Please login or sign up before buying this product.',
  'login.before_cart': 'Please login or sign up before using your cart.',
  'login.before_cart_add': 'Please login or sign up before adding products to cart.',
  'login.before_checkout': 'Please login or sign up before checkout.',
  'login.before_open_cart': 'Please login or sign up before opening cart.',
  'login.before_section': 'Please login or sign up to view this section.',
  'login.before_wishlist': 'Please login or sign up to use your wishlist.',
  'login.button': 'Login / Signup',
  'login.required_message': 'Please login or create an account to continue.',
  'login.required_title': 'Login Required',
  'login.view_cart': 'Please login or create an account to view your cart.',
  'login.view_history': 'Please login or create an account to view your order history.',
  'login.view_orders': 'Please login or create an account to view your orders.',
  'login.write_review': 'Please login to write a review.',

  // --- menu --------------------------------------------------------------------
  'menu.account': 'Account',
  'menu.addresses': 'My Addresses',
  'menu.change_password': 'Change Password',
  'menu.edit_profile': 'Edit Profile',
  'menu.invoices': 'Invoices',
  'menu.language': 'Language',
  'menu.logout': 'Logout',
  'menu.my_reviews': 'My Reviews',
  'menu.notifications': 'Notifications',
  'menu.offers': 'Offers & Coupons',
  'menu.order_history': 'Order History',
  'menu.returns': 'Returns',
  'menu.support': 'Support',
  'menu.wishlist': 'Wishlist',

  // --- nav ---------------------------------------------------------------------
  'nav.cart': 'Cart',
  'nav.category': 'Category',
  'nav.home': 'Home',
  'nav.menu': 'Menu',
  'nav.orders': 'Orders',

  // --- notifications -----------------------------------------------------------
  'notifications.empty_customer': 'Order updates and offers will show up here.',
  'notifications.empty_title': 'No notifications',
  'notifications.loading': 'Loading notifications...',
  'notifications.mark_all_read': 'Mark all read',
  'notifications.title': 'Notifications',

  // --- offers ------------------------------------------------------------------
  'offers.code_copied': '{code} copied to the coupon box.',
  'offers.coupon': 'Coupon',
  'offers.empty_message': 'Check back soon for coupons and seasonal promotions.',
  'offers.empty_title': 'No offers right now',
  'offers.enter_code': 'Enter a coupon code.',
  'offers.flat_off': 'FLAT {n} OFF',
  'offers.loading': 'Loading offers...',
  'offers.min_order': 'Min {amount}',
  'offers.percent_off': '{n}% OFF',

  // --- orders ------------------------------------------------------------------
  'orders.add_to_cart': 'Add to cart',
  'orders.added_from_order': '{n} product(s) from {order}',
  'orders.added_to_cart_title': 'Added to cart',
  'orders.all': 'All',
  'orders.all_time': 'All time',
  'orders.approved': 'Approved',
  'orders.arriving_soon': 'Arriving soon',
  'orders.being_packed': 'Being packed',
  'orders.buy_again': 'Buy Again',
  'orders.buy_again_message': 'Products from your orders will appear here.',
  'orders.cancel_not_reversible': 'This cannot be undone. Please tell us why you are cancelling.',
  'orders.cancel_order': 'Cancel Order',
  'orders.cancellation_reason': 'Reason for cancelling',
  'orders.cancelled': 'Cancelled',
  'orders.confirmed': 'Order confirmed',
  'orders.current': 'Order Details',
  'orders.delivered': 'Delivered',
  'orders.delivered_on': 'Delivered {date}',
  'orders.details': 'Details',
  'orders.dispatched': 'Dispatched',
  'orders.empty_message': 'Try a different search, tab or time period.',
  'orders.in_review': 'In Review',
  'orders.invoice': 'Invoice',
  'orders.last_30_days': 'Last 30 days',
  'orders.last_3_months': 'Last 3 months',
  'orders.no_current_message': 'Orders you place stay here until they are delivered.',
  'orders.no_current_title': 'No Current Orders',
  'orders.no_match_title': 'No matching orders',
  'orders.no_past_message': 'Delivered and cancelled orders will appear here.',
  'orders.no_past_title': 'No Past Orders',
  'orders.nothing_to_buy_again': 'Nothing to buy again',
  'orders.on_the_way': 'On the way',
  'orders.order_cancelled': 'Order Cancelled',
  'orders.order_cancelled_message': '{order} has been cancelled.',
  'orders.order_items': 'Order items',
  'orders.out_for_delivery': 'Out for Delivery',
  'orders.out_for_delivery_short': 'Out for delivery',
  'orders.packing': 'Packing',
  'orders.return': 'Return',
  'orders.return_order': 'Return {order}',
  'orders.return_received': 'We received your return request for {order}.',
  'orders.return_requested': 'Return requested',
  'orders.review': 'Review',
  'orders.search_hint': 'Search current orders',
  'orders.search_history_hint': 'Search past orders or products',
  'orders.tell_why_cancelling': 'Please tell us why you are cancelling.',
  'orders.this_year': 'This year',
  'orders.time_period': 'Time period',
  'orders.track_short': 'Track',
  'orders.tracking_history': 'Tracking History',
  'orders.unavailable_products': 'These products are no longer available.',
  'orders.under_review': 'Under Review',

  // --- password ----------------------------------------------------------------
  'password.at_least': 'At least {n} characters.',
  'password.change_failed': 'Change Failed',
  'password.changed': 'Password Changed',
  'password.changed_message': 'Use your new password next time you log in.',
  'password.enter_current': 'Enter your current password.',
  'password.intro_existing': 'Enter your current password, then choose a new one.',
  'password.intro_otp': 'You sign in with mobile OTP, so no current password is needed. Choose a password for your account.',
  'password.min_length': 'New password must be at least {n} characters.',
  'password.no_match': 'Does not match',
  'password.no_match_message': 'New password and confirm password must be the same.',
  'password.too_short': 'Too short',
  'password.update': 'Update Password',

  // --- profile -----------------------------------------------------------------
  'profile.choose_gallery': 'Choose from Gallery',
  'profile.dob': 'Date of Birth',
  'profile.dob_optional': 'Date of Birth (optional)',
  'profile.edit': 'Edit profile',
  'profile.enter_name': 'Enter your name.',
  'profile.mobile_locked': 'Mobile number cannot be changed.',
  'profile.photo_updated': 'Photo Updated',
  'profile.photo_updated_message': 'Your profile photo has been changed.',
  'profile.preferred_language': 'Preferred Language',
  'profile.save_changes': 'Save Changes',
  'profile.select_date': 'Select date',
  'profile.take_photo': 'Take Photo',
  'profile.update_failed': 'Update Failed',
  'profile.updated': 'Profile Updated',
  'profile.updated_message': 'Your profile details have been saved.',
  'profile.upload_failed': 'Upload Failed',

  // --- returns -----------------------------------------------------------------
  'returns.empty_message': 'Raise a return from any delivered order within 7 days.',
  'returns.empty_title': 'No returns',
  'returns.loading': 'Loading returns...',
  'returns.order_no': 'Order {order}',
  'returns.reason': 'Reason for return',
  'returns.refund': 'Refund {amount}',
  'returns.submit': 'Submit Return Request',
  'returns.submitted': 'Your return request has been submitted.',
  'returns.tell_why': 'Tell us why you are returning this order.',
  'returns.title': 'Returns',
  'returns.window': 'Returns are accepted within {n} days of delivery.',

  // --- reviews -----------------------------------------------------------------
  'reviews.body_optional': 'What did you think? (optional)',
  'reviews.count': '({n} reviews)',
  'reviews.empty': 'No reviews yet. Be the first to rate this product.',
  'reviews.empty_message': 'Reviews you write for products will appear here.',
  'reviews.empty_title': 'No Reviews Yet',
  'reviews.loading': 'Loading your reviews...',
  'reviews.moderation': 'Reviews are published after a quick moderation check.',
  'reviews.my_reviews': 'My Reviews',
  'reviews.no_product': 'No product selected.',
  'reviews.pending_note': 'Awaiting admin approval before it appears on the product page.',
  'reviews.submit': 'Submit Review',
  'reviews.tap_star': 'Tap a star to rate this product.',
  'reviews.thanks': 'Thanks! Your review will appear once approved.',
  'reviews.title': 'Ratings & Reviews',
  'reviews.title_optional': 'Title (optional)',
  'reviews.write': 'Write a review',
  'reviews.write_title': 'Write a Review',
  'reviews.your_rating': 'Your rating',

  // --- shell -------------------------------------------------------------------
  'shell.categories': 'Categories',
  'shell.shop': 'Dr. Bawasakar Shop',
  'shell.welcome': 'Welcome, {name}',

  // --- support -----------------------------------------------------------------
  'support.create_ticket': 'Create Ticket',
  'support.enter_subject_message': 'Enter subject and message.',
  'support.failed': 'Support Failed',
  'support.need_help': 'Need Help',
  'support.sent': 'Support Sent',
  'support.sent_message': 'Your support ticket has been created.',
  'support.subject': 'Subject',

  // --- tracking ----------------------------------------------------------------
  'tracking.cancelled_note': 'This order was cancelled. Contact support for help with a replacement or refund.',
  'tracking.code': 'Tracking Code',
  'tracking.courier': 'Courier',
  'tracking.deliver_to': 'Deliver To',
  'tracking.details_title': 'Order Details',
  'tracking.destination': 'Destination',
  'tracking.from': 'From',
  'tracking.items_count': 'Items ({n})',
  'tracking.last_update': 'Last Update',
  'tracking.link_copied': 'Courier tracking link copied',
  'tracking.loading': 'Fetching order status...',
  'tracking.no_order': 'No order selected.',
  'tracking.no_updates': 'No tracking updates yet.',
  'tracking.no_updates_short': 'No updates yet.',
  'tracking.not_found': 'We could not find tracking details for this order.',
  'tracking.order': 'Order',
  'tracking.order_received': 'Order received',
  'tracking.package': 'Package',
  'tracking.package_summary': '{n} item(s) · {amount}',
  'tracking.payment_status': 'Payment Status',
  'tracking.placed_on': 'Placed on',
  'tracking.price': 'Price {amount}',
  'tracking.progress': 'Order Progress',
  'tracking.review_desk': 'Order review desk',
  'tracking.tap_copy': 'Tap to copy tracking link',
  'tracking.title': 'Track Order',
  'tracking.track_order': 'Track Order',
  'tracking.unavailable': 'Cannot track this order',
  'tracking.view_details': 'Order Details',
  'tracking.with_partner': 'With delivery partner, on the way to you',

  // --- wishlist ----------------------------------------------------------------
  'wishlist.empty_message': 'Tap the heart on any product to keep it here for later.',
  'wishlist.empty_title': 'Nothing saved yet',
  'wishlist.loading': 'Loading your wishlist...',
  'wishlist.unavailable': 'Currently unavailable',
  // --- location ----------------------------------------------------------------
  'location.city_village': 'City / Village',
  'location.district': 'District',
  'location.enter_city': 'Please enter city or village',
  'location.enter_taluka': 'Please type the taluka name',
  'location.invalid_pincode': 'Pincode must be 6 digits',
  'location.load_failed': 'Could not load locations. Check your internet and try again.',
  'location.other_taluka': 'Other (type taluka)',
  'location.pincode': 'Pincode',
  'location.select_district': 'Please select district',
  'location.select_state': 'Please select state',
  'location.select_taluka': 'Please select taluka',
  'location.state': 'State',
  'location.taluka': 'Sub-district / Taluka',
  'location.taluka_name': 'Taluka name',
  'location.title': 'Location',
};
